name: wheels

on:
  pull_request:
    paths:
      - "packaging/compute_wheel_version.sh"
      - ".github/workflows/wheel*"
      - "setup.py"
      - "requirements*.txt"
  push:
    branches:
      - main
    tags:
      - "v[0-9]+*"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - 8-core-ubuntu
          - windows-8-core
        python:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
        torch_version:
          - "2.1.0"
        cuda_short_version:
          - "118"
          - "121"
        include:
          - sdist: false
            publish: false
          # Publish source distribution only from this runner
          - os: 8-core-ubuntu
            python: "3.10"
            torch_version: "2.1.0"
            sdist: true
          # Set version to publish to pypi
          - torch_version: "2.1.0"
            cuda_short_version: "118"
            publish: true

    uses: ./.github/workflows/wheels_reusable.yml
    if: github.repository == 'facebookresearch/xformers' || github.event_name == 'pull_request'
    with:
      os: ${{ matrix.os }}
      python: ${{ matrix.python }}
      torch_version: ${{ matrix.torch_version }}
      cuda_short_version: ${{ matrix.cuda_short_version }}
      publish: ${{ matrix.publish == true && github.event_name != 'pull_request'}}
      sdist: ${{ matrix.sdist == true }}
      twine_username: __token__
    secrets:
      twine_password: ${{ secrets.PYPI_TOKEN }}
