name: win-build

on:
  pull_request: {}

env:
  TORCH_CUDA_ARCH_LIST: "8.0"
  FORCE_CUDA: 1
  MAX_JOBS: 4
  DISTUTILS_USE_SDK: 1 # otherwise distutils will complain on windows about multiple versions of msvc
  XFORMERS_BUILD_TYPE: "Release"
  XFORMERS_DISABLE_FLASH_ATTN: 1

jobs:
  win_build:
    name: win-build
    runs-on: windows-2019
    env:
      PY: python3

    timeout-minutes: 360
    defaults:
      run:
        shell: bash
    steps:
      - name: Recursive checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          path: "."

      - name: Setup Runner
        uses: ./.github/actions/setup-windows-runner
        with:
          cuda: "11.7.1"
          python: "3.7"

      - name: Install build dependencies
        run: |
          $PY -m pip install wheel setuptools ninja torch==1.13 -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cu117
          git config --global --add safe.directory "*"
          $PY -c "import torch; print('torch', torch.__version__)"
          $PY -c "import torch; print('torch.cuda', torch.version.cuda)"

      - name: Build
        run: $PY setup.py develop
